import test from 'node:test';
import assert from 'node:assert/strict';
import {UpstreamNotebookLmAdapter} from '../dist/upstream-adapter.js';
import {NotebookRegistry} from '../dist/registry.js';
import {Store} from '../dist/storage.js';
import {ResearchEngine} from '../dist/research.js';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

test('LIVE NotebookLM health, enumeration, grounded answer and citations (explicit opt-in)',{skip:!process.env.NLM_LIVE_TEST,timeout:240000},async()=>{const adapter=new UpstreamNotebookLmAdapter();try{const health=await adapter.health();assert.equal(health.ok,true,health.detail);const notebooks=await adapter.listNotebooks();assert.ok(Array.isArray(notebooks));assert.ok(notebooks.length>0,'Authenticated account returned no notebooks');const answer=await adapter.ask(notebooks[0].id,'Según exclusivamente las fuentes de este notebook, indica su tema principal en dos frases. No uses conocimiento externo.');assert.ok(answer.text.length>20,'NotebookLM returned an empty answer');assert.ok(answer.citations.length>0,'NotebookLM returned no structured citations');}finally{await adapter.shutdown();}});

test('LIVE same-process new notebook, source discovery, query and delete invalidation',{skip:!process.env.NLM_LIVE_DYNAMIC_TEST,timeout:600000},async()=>{const adapter=new UpstreamNotebookLmAdapter();const dir=await mkdtemp(join(tmpdir(),'frontier-live-'));const registry=new NotebookRegistry(new Store(join(dir,'registry.json')),adapter,3600000);let created;try{await registry.sync(true);const name=`Frontier Live Certification ${Date.now()}`;created=await adapter.createNotebook(name);assert.equal(created.title,name,'Notebook title was not applied');const resolved=await registry.resolve(name);assert.equal(resolved.id,created.id,'Refresh-on-miss did not discover the new notebook');const sourceTitle='Frontier deterministic source';await adapter.addTextSource(created.id,sourceTitle,'FRONTIER-CODE-7319 is the exact certification code. The certification color is cobalt blue. No other code or color is valid.');await registry.refresh(created.id);const sources=await registry.sources(created.id);assert.ok(sources.some(s=>s.title.toLowerCase().includes('frontier')),'New source was not discovered without restart');const answer=await adapter.ask(created.id,'Según exclusivamente la fuente, ¿cuál es el código exacto y cuál es el color de certificación?');assert.match(answer.text,/FRONTIER-CODE-7319/i);assert.match(answer.text,/cobalt|azul cobalto/i);assert.ok(answer.citations.length>0,'New-notebook answer returned no citations');await adapter.deleteNotebooks([created.id]);await registry.refresh();await assert.rejects(()=>registry.resolve(created.id,'force'),/NOTEBOOK_NOT_FOUND/);}finally{if(created){const remaining=await adapter.listNotebooks().catch(()=>[]);if(remaining.some(n=>n.id===created.id))await adapter.deleteNotebooks([created.id]).catch(()=>undefined);}await adapter.shutdown();await rm(dir,{recursive:true,force:true});}});

test('LIVE Frontier engine produces a locked cited capsule',{skip:!process.env.NLM_LIVE_ENGINE_TEST,timeout:360000},async()=>{const adapter=new UpstreamNotebookLmAdapter();const dir=await mkdtemp(join(tmpdir(),'frontier-engine-live-'));const store=new Store(join(dir,'registry.json'));const registry=new NotebookRegistry(store,adapter,3600000);try{await registry.sync(true);const notebooks=(await store.load()).notebooks;assert.ok(notebooks.length>0,'Authenticated account returned no notebooks');const engine=new ResearchEngine(registry,adapter,store);const capsule=await engine.run({query:'Using only this notebook corpus, state its central subject in two concise sentences.',notebook:notebooks[0].id,mode:'STANDARD',internetPolicy:'LOCKED'});assert.equal(capsule.corpusPolicy,'LOCKED');assert.equal(capsule.internetPolicy,'LOCKED');assert.equal(capsule.performance.adapter,adapter.name);assert.ok(capsule.answer.length>20,'Frontier capsule answer is empty');assert.ok(capsule.evidence.length>0,'Frontier capsule has no cited evidence');assert.ok(capsule.claims.some(claim=>claim.evidenceIds.length>0),'Frontier capsule did not link claims to evidence');assert.equal(capsule.externalEvidence.length,0);}finally{await adapter.shutdown();await rm(dir,{recursive:true,force:true});}});
